const APP_ROUTES = {
  HOME: "/",
  SIGN_IN: "/sign-in",
  SIGN_UP: "/sign-up",
  RESET_PASSWORD: "/reset-password",
  ACCOUNT: "/account",
  ACCOUNT_SETTINGS: "/account/settings",
  ACCOUNT_SUBSCRIPTIONS: "/account/subscriptions",
  PRODUCTS: "/products",
  PRODUCT: "/products/:id",
  PURCHASE: "/purchase",
  PURCHASE_CART: "cart",
  PURCHASE_ADDRESS: "cart/address",
  PURCHASE_CHECKOUT: "cart/address/checkout",
  TO_CART: "/purchase/cart",
  TO_ADDRESS: "/purchase/cart/address",
  TO_CHECKOUT: "/purchase/cart/address/checkout",
  SUCCESS: "/success",
  ADMIN: "/admin",
  ADMIN_DASHBOARD: "dashboard",
  ADMIN_PROMOTION_CAROUSEL: "promotions-carousel",
  ADMIN_PRODUCTS: "products",
  ADMIN_PRODUCT: "products/:id",
  ADMIN_PRODUCT_TRANSLATION: "products/:id/translations/:locale",
  ADMIN_CATEGORIES: "categories",
  ADMIN_USERS_ADMINS: "users/admins",
  ADMIN_USERS_CLIENTS: "users/clients",
} as const;

const API_ROUTES = {
  URL: "http://localhost:8000",
  SIGN_UP: "/api/auth/register",
  SIGN_IN: "/api/auth/login",
  ME: "/api/auth/me",
  REFRESH: "/api/auth/refresh",
  SIGN_OUT: "/api/auth/logout",
  REQUEST_RESET_PASSWORD: "/api/auth/send-reset",
  RESET_PASSWORD: "/api/auth/reset-password",
  USER_NEW_ADMIN: "/api/users/add-admin",
  USER_UPDATE_INFOS: "/api/users/update",
  USER_UPDATE_PASSWORD: "/api/users/update-password",
  USER_ADDRESS_NEW: "/api/addresses/add",
  USER_ADDRESS_GET_ALL: "/api/addresses/get-all",
  USER_ADDRESS_UPDATE: "/api/addresses/update",
  USER_ADDRESS_DELETE: "/api/addresses/delete",
  PRODUCT_GET: "/api/products/get",
  PRODUCT_GET_ALL: "/api/products/get-all",
  PRODUCT_NEW: "/api/products/add",
  PRODUCT_NEW_TRANSLATION: "/api/products/add/details",
  PRODUCT_UPDATE: "/api/products/update",
  PRODUCT_UPDATE_TRANSLATION: "/api/products/update/details",
  PRODUCT_DELETE: "/api/products/delete",
  PRODUCT_DELETE_TRANSLATION: "/api/products/delete/details",
  CATEGORY_GET_ALL: "/api/categories/get-all-locales",
  CATEGORY_NEW: "/api/categories/add",
  CATEGORY_NEW_LOCALE: "/api/categories/add-locale",
  CATEGORY_UPDATE_LOCALE: "/api/categories/update-locale",
  CATEGORY_DELETE: "/api/categories",
  CATEGORY_DELETE_LOCALE: "/api/categories/delete-locale",
  CART_GET: "/api/orders/get-cart",
  CART_UPDATE: "/api/orders/update-order",
  CART_NEW_ITEM: "/api/orders/add-product",
  CART_UPDATE_ITEM: "/api/orders/update-cart-item",
  CART_DELETE_ITEM: "/api/orders/delete-cart-item",
  PROMOTION_CAROUSEL_TEXT_NEW: "/api/home-texts",
  PROMOTION_CAROUSEL_TEXT_GET_ALL: "/api/home-texts",
  PROMOTION_CAROUSEL_TEXT_UPDATE: "/api/home-texts",
} as const;

export { APP_ROUTES, API_ROUTES };
