const BASE_URL = import.meta.env.VITE_API_BASE_URL;

const APP_ROUTES = {
  HOME: "/",
  SIGN_IN: "/sign-in",
  SIGN_UP: "/sign-up",
  RESET_PASSWORD: "/reset-password",
  ACCOUNT: "account",
  ACCOUNT_SETTINGS: "/account/settings",
  ACCOUNT_SUBSCRIPTIONS: "/account/subscriptions",
  ACCOUNT_HISTORY: "/account/history",
  PRODUCTS: "/products",
  PRODUCT: "/products/:id",
  PURCHASE: "/purchase",
  PURCHASE_CART: "/purchase/cart",
  PURCHASE_ADDRESS: "/purchase/cart/address",
  PURCHASE_CHECKOUT: "/purchase/cart/address/checkout",
  CHECKOUT_SUCCESS: "/purchase/cart/address/checkout/success",
  ADMIN: "/admin",
  ADMIN_DASHBOARD_SALES: "/admin/dashboard/sales",
  ADMIN_DASHBOARD_CUSTOMERS: "/admin/dashboard/customers",
  ADMIN_SUPPORT_TICKETS: "/admin/support/tickets",
  ADMIN_SUPPORT_CHATBOT: "/admin/support/chatbot",
  ADMIN_SETTINGS_GENERAL: "/admin/settings/general",
  ADMIN_SETTINGS_PAYMENTS: "/admin/settings/payments",
  ADMIN_SETTINGS_LANGUAGES: "/admin/settings/languages",
  ADMIN_PROMOTION_CAROUSEL: "/admin/promotions-carousel",
  ADMIN_PRODUCTS: "/admin/products",
  ADMIN_PRODUCT: "/admin/products/:id",
  ADMIN_PRODUCT_TRANSLATION: "/admin/products/:id/translations/:locale",
  ADMIN_CATEGORIES: "/admin/categories",
  ADMIN_USERS_ADMINS: "/admin/users/admins",
  ADMIN_USERS_CLIENTS: "/admin/users/clients",
  LEGAL_TERMS_OF_USE: "legal/terms-of-use",
  LEGAL_NOTICE: "legal/notice",
} as const;

const API_ROUTES = {
  URL: BASE_URL,
  SIGN_UP: "/api/auth/register",
  SIGN_IN: "/api/auth/login",
  ME: "/api/auth/me",
  REFRESH: "/api/auth/refresh",
  SIGN_OUT: "/api/auth/logout",
  REQUEST_RESET_PASSWORD: "/api/auth/send-reset",
  RESET_PASSWORD: "/api/auth/reset-password",
  USER_NEW_ADMIN: "/api/users/add-admin",
  USER_UPDATE_INFOS: "/api/users/update",
  USER_UPDATE_PASSWORD: "/api/users/update-password",
  USER_ADDRESS_NEW: "/api/addresses/add",
  USER_ADDRESS_GET_ALL: "/api/addresses/get-all",
  USER_ADDRESS_UPDATE: "/api/addresses/update",
  USER_ADDRESS_DELETE: "/api/addresses/delete",
  USER_SUBSCRIPTIONS_GET_ALL: "/api/subscriptions/my",
  USER_SUBSCRIPTIONS_UPDATE_STATUS: "/api/subscriptions/status",
  USER_SUBSCRIPTIONS_CANCEL: "/api/subscriptions/cancel",
  USER_HISTORY_GET_ALL: "/api/payments/user",
  PRODUCT_GET: "/api/products/get",
  PRODUCT_GET_ALL: "/api/products/get-all",
  PRODUCT_GET_BEST_SELLER: "/api/products/best-seller",
  PRODUCT_NEW: "/api/products/add",
  PRODUCT_NEW_TRANSLATION: "/api/products/add/details",
  PRODUCT_UPDATE: "/api/products/update",
  PRODUCT_UPDATE_TRANSLATION: "/api/products/update/details",
  PRODUCT_DELETE: "/api/products/delete",
  PRODUCT_DELETE_TRANSLATION: "/api/products/delete/details",
  CATEGORY_GET_ALL: "/api/categories/get-all-locales",
  CATEGORY_NEW: "/api/categories/add",
  CATEGORY_NEW_LOCALE: "/api/categories/add-locale",
  CATEGORY_UPDATE_LOCALE: "/api/categories/update-locale",
  CATEGORY_DELETE: "/api/categories",
  CATEGORY_DELETE_LOCALE: "/api/categories/delete-locale",
  CART_GET: "/api/orders/get-cart",
  CART_UPDATE: "/api/orders/update-order",
  CART_NEW_ITEM: "/api/orders/add-product",
  CART_UPDATE_ITEM: "/api/orders/update-cart-item",
  CART_UPDATE_STATUS: "/api/orders/update-order-status",
  CART_DELETE_ITEM: "/api/orders/delete-cart-item",
  PROMOTION_CAROUSEL_TEXT_NEW: "/api/home-texts",
  PROMOTION_CAROUSEL_TEXT_GET_ALL: "/api/home-texts",
  PROMOTION_CAROUSEL_TEXT_UPDATE: "/api/home-texts",
  PURCHASE_CHECKOUT: "/api/checking",
  PURCHASE_INTENT_CANCEL: "/api/checking/cancel-setup-intent",
  PURCHASE_INTENT_NEW: "/api/checking/create-setup-intent",
  METRICS_SALES: "/api/payments/metrics/sales",
  METRICS_SALES_BY_CATEGORY: "/api/payments/metrics/categories",
} as const;

export { APP_ROUTES, API_ROUTES };
