const APP_ROUTES = {
  HOME: "/",
  SIGN_IN: "/sign-in",
  SIGN_UP: "/sign-up",
  RESET_PASSWORD: "/reset-password",
  ACCOUNT: "/account",
  ACCOUNT_SETTINGS: "/account/settings",
  ACCOUNT_SUBSCRIPTIONS: "/account/subscriptions",
  PRODUCTS: "/products",
  PRODUCT: "/products/:id",
  CART: "/cart",
  ADMIN: "/admin",
  ADMIN_DASHBOARD: "dashboard",
  ADMIN_PRODUCTS: "products",
  ADMIN_PRODUCT: "products/:id",
  ADMIN_PRODUCT_TRANSLATION: "products/:id/translations/:locale",
  ADMIN_CATEGORIES: "categories",
} as const;

const API_ROUTES = {
  URL: "http://localhost:8000",
  SIGN_UP: "/api/auth/register",
  SIGN_IN: "/api/auth/login",
  ME: "/api/auth/me",
  REFRESH: "/api/auth/refresh",
  SIGN_OUT: "/api/auth/logout",
  USER_UPDATE_INFOS: "/api/users/update",
  USER_UPDATE_PASSWORD: "/api/users/update-password",
  PRODUCT_GET: "/api/products/get",
  PRODUCT_GET_ALL: "/api/products/get-all",
  PRODUCT_NEW: "/api/products/add",
  PRODUCT_NEW_TRANSLATION: "/api/products/add/details",
  PRODUCT_UPDATE: "/api/products/update",
  PRODUCT_UPDATE_TRANSLATION: "/api/products/update/details",
  PRODUCT_DELETE: "/api/products/delete",
  PRODUCT_DELETE_TRANSLATION: "/api/products/delete/details",
  CATEGORY_GET_ALL: "/api/categories/get-all-locales",
  CATEGORY_NEW: "/api/categories/add",
  CATEGORY_NEW_LOCALE: "/api/categories/add-locale",
  CATEGORY_UPDATE_LOCALE: "/api/categories/update-locale",
  CATEGORY_DELETE: "/api/categories",
  CATEGORY_DELETE_LOCALE: "/api/categories/delete-locale",
  CART_GET: "/api/orders/get-cart",
  CART_NEW_ITEM: "/api/orders/add-product",
  CART_UPDATE_ITEM: "/api/orders/update-cart-item",
  CART_DELETE_ITEM: "/api/orders/delete-cart-item",
} as const;

export { APP_ROUTES, API_ROUTES };
